name: lab5-build-pipeline

trigger: none

pool:
  #vmImage: 'ubuntu-22.04'
  name: desktop   # using custom build agent - or - vmImage: 'ubuntu-latest'  # if using Microsoft-hosted agent
  
steps:
# Copy files from a source folder to a target folder using patterns matching file paths (not folder paths)
- task: CopyFiles@2
  inputs:
    contents: '**/*.sh' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true # Optional

# Publish script files as build artifacts
- task: PublishPipelineArtifact@1
  inputs:
    path: '$(Build.ArtifactStagingDirectory)'
    artifact: 'bashscripts'